spring:
  profiles:
    active: dev
  messages:
    basename: org/springframework/security/messages
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.107.41:3306/hsdm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
hdms:
  storage:
    location: D:/hdms
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
---
spring:
  profiles: dev
logging:
  level:
    com.honvay: debug
server:
  port: 8091
---
spring:
  profiles: prod
server:
  port: 9090